name = "server"
type = "webpack"
workers_dev = true
account_id = "d30324e4c93b1db17e4145f17a16ded8"
zone_id = "da69c4dd2392e14ee200f98f22d6438f"
kv_namespaces = [
    { binding = "BUCKET", id = "97e061d7daa7405d86e3fdd85599096a"}
]

[env.staging]
name = "drive-staging"
